FROM golang:1.16.0-buster

RUN apt-get update

RUN go get github.com/go-delve/delve/cmd/dlv

ENV SOURCE_DIR /go-doru

COPY go.mod go.sum ${SOURCE_DIR}/
RUN cd ${SOURCE_DIR} && go mod download

COPY . ${SOURCE_DIR}

RUN cd ${SOURCE_DIR} \
  && CGO_ENABLE=0 GOOS=linux go build -gcflags "all=-N -l" -o doru cmd/doru/main.go

FROM debian:buster
LABEL maintainer="Mosaic Labs <ben@mosaiclabs.eu>"

ENV SOURCE_DIR /go-doru
COPY --from=0 /go/bin/dlv /usr/local/bin/dlv
COPY --from=0 ${SOURCE_DIR}/doru /usr/local/bin/doru

EXPOSE 1414
EXPOSE 40000

ENV DORU_PATH /data/doru
RUN adduser --home ${DORU_PATH} --disabled-login --gecos "" --ingroup users doru

USER doru

VOLUME ${DORU_PATH}

ENTRYPOINT ["dlv", "--listen=0.0.0.0:40000", "--headless=true", "--accept-multiclient", "--continue", "--api-version=2", "exec", "/usr/local/bin/doru"]

CMD ["--"]
